### PR TITLE
Actually write the config to .config on Linux

### PR DESCRIPTION
**Pull request by unascribed**

### CODE REVIEW

**Comment by unascribed** [comment]
:-1:

horrible maintainers, worst project ever, would not PR again

**Comment by Minecrell** [comment]
Please update for master changes.

**Comment by jamierocks** [comment]
https://github.com/LapisBlue/Nocturne/commit/00ca7cb2a561372eb129e19efd9580186ab70332

**Comment by Minecrell** [comment]
@jamierocks That does not fix the problem, it should be in `.config/nocturne` or `.config/Nocturne`.

**Comment by Minecrell** [comment]
Fixed in https://github.com/LapisBlue/Nocturne/commit/3e81d7153487eb3f68f2485b67e3e5ca18b092fa

**Comment by caseif** [comment]
Well this is quite a clusterfuck of a PR.

**Pull request closed without merging**
